services:
  app:
    image: ghcr.io/joinchang/lxns-homepage:latest
    environment:
      NODE_ENV: "production"
      BETTER_AUTH_URL: "https://lxns.net"

  worker:
    image: ghcr.io/joinchang/lxns-homepage:latest
    environment:
      NODE_ENV: "production"
